package com.champsoft.restaurantreservationssystem.customer.domain.model;

public record CustomerId(Long value) {

    public CustomerId {
        if (value != null && value <= 0)
            throw new IllegalArgumentException("CustomerId must be positive");
    }

    public static CustomerId newId() {
        // ID will be generated by the database
        return new CustomerId(null);
    }

    public static CustomerId of(Long value) {
        return new CustomerId(value);
    }

    @Override
    public String toString() {
        return value == null ? "null" : value.toString();
    }
}
