spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: customers-service
                          uri: http://localhost:8081
                          predicates:
                              - Path=/api/customers/**

                        - id: menu_items-service
                          uri: http://localhost:8082
                          predicates:
                              - Path=/api/menu-items/**

                        - id: table-service
                          uri: http://localhost:8083
                          predicates:
                              - Path=/api/tables/**

                        - id: reservation-service
                          uri: http://localhost:8084
                          predicates:
                              - Path=/api/reservations/**

server:
    port: 8080

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        urls:
            - name: customers-service
              url: http://localhost:8081/v3/api-docs

            - name: menu_items-service
              url: http://localhost:8082/v3/api-docs

            - name: table-service
              url: http://localhost:8083/v3/api-docs

            - name: reservation-service
              url: http://localhost:8084/v3/api-docs