package com.champsoft.restaurantreservationssystem.menu.application.service;

import com.champsoft.restaurantreservationssystem.menu.application.exception.MenuItemNotFoundException;
import com.champsoft.restaurantreservationssystem.menu.application.port.out.MenuItemRepositoryPort;
import com.champsoft.restaurantreservationssystem.menu.domain.model.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;

@Service
public class MenuItemCrudService {

    private final MenuItemRepositoryPort repo;

    public MenuItemCrudService(MenuItemRepositoryPort repo) {
        this.repo = repo;
    }

    @Transactional
    public MenuItem create(String name, BigDecimal price) {
        var item = new MenuItem(
                MenuItemId.newId(), // ID generated by DB
                new MenuItemName(name),
                new MenuItemPrice(price)
        );
        return repo.save(item);
    }

    @Transactional(readOnly = true)
    public MenuItem getById(Long id) {
        return repo.findById(id)
                .orElseThrow(() -> new MenuItemNotFoundException(id));
    }

    @Transactional(readOnly = true)
    public List<MenuItem> list() {
        return repo.findAll();
    }

    @Transactional
    public MenuItem update(Long id, String name, BigDecimal price) {
        var item = getById(id);
        item.update(
                new MenuItemName(name),
                new MenuItemPrice(price)
        );
        return repo.save(item);
    }

    @Transactional
    public void delete(Long id) {
        getById(id); // ensures exception if missing
        repo.deleteById(id);
    }
}
