-- Add identity generation to customers, restaurant_tables, and menu_items
-- so JPA can generate IDs on insert.

ALTER TABLE customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE restaurant_tables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE menu_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Seed data occupies IDs 1-10; restart sequences past that.
ALTER SEQUENCE customers_id_seq RESTART WITH 11;
ALTER SEQUENCE restaurant_tables_id_seq RESTART WITH 11;
ALTER SEQUENCE menu_items_id_seq RESTART WITH 11;
ALTER SEQUENCE reservations_id_seq RESTART WITH 11;
ALTER SEQUENCE pre_order_items_id_seq RESTART WITH 11;
