spring:
  datasource:
    url: jdbc:h2:mem:reservation-test-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 0

services:
  customers:
    base-url: http://localhost:9991
  menu-items:
    base-url: http://localhost:9992
  tables:
    base-url: http://localhost:9993

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

